### ISSUE TITLE
PCIe bw modelling

### ISSUE THREAD

**Issue by Yfeng-44** [csl-iisc/SBRP-ASPLOS23#1]
Hi,
Thank you so much for opensource the code. I wonder how the PCIe bandwidth and latency is simulated here.

Thanks

**Comment by AKKamath** [comment]
To simulate the PCIe latency, we increase the PM access latency here:  https://github.com/csl-iisc/SBRP-ASPLOS23/blob/0ce2de799f4ac18608ed2a01546fbeee457e5490/models/sbrp_far/gpgpusim.config#L146
For PCIe bandwidth, we scale down the PM bandwidth here: https://github.com/csl-iisc/SBRP-ASPLOS23/blob/0ce2de799f4ac18608ed2a01546fbeee457e5490/models/sbrp_far/gpgpusim.config#L188C19-L188C19

**Comment by Yfeng-44** [comment]
Thank you for your reply!
